/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as DashboardTanstackDbExampleRouteImport } from './routes/dashboard/tanstack-db-example'
import { Route as DashboardProtectExamplesRouteImport } from './routes/dashboard/protect-examples'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as DashboardWorkspaceIndexRouteImport } from './routes/dashboard/workspace/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSettingsEnhancedIndexRouteImport } from './routes/dashboard/settings-enhanced/index'
import { Route as DashboardChatIndexRouteImport } from './routes/dashboard/chat/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as authTwoFactorIndexRouteImport } from './routes/(auth)/two-factor/index'
import { Route as DashboardChatVercelRouteImport } from './routes/dashboard/chat/vercel'
import { Route as DashboardChatRagRouteImport } from './routes/dashboard/chat/rag'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as authTwoFactorOtpRouteImport } from './routes/(auth)/two-factor/otp'
import { Route as authAcceptInvitationInvitationIdIndexRouteImport } from './routes/(auth)/accept-invitation/$invitationId/index'
import { Route as ApiAiVercelChatRouteImport } from './routes/api/ai/vercel/chat'
import { Route as ApiAiMcpTransportRouteImport } from './routes/api/ai/mcp/$transport'
import { Route as ApiAiChatRagRouteImport } from './routes/api/ai/chat.rag'
import { Route as ApiAiChatImageGenerationRouteImport } from './routes/api/ai/chat.image.generation'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTanstackDbExampleRoute =
  DashboardTanstackDbExampleRouteImport.update({
    id: '/tanstack-db-example',
    path: '/tanstack-db-example',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProtectExamplesRoute =
  DashboardProtectExamplesRouteImport.update({
    id: '/protect-examples',
    path: '/protect-examples',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceIndexRoute = DashboardWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsEnhancedIndexRoute =
  DashboardSettingsEnhancedIndexRouteImport.update({
    id: '/settings-enhanced/',
    path: '/settings-enhanced/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardChatIndexRoute = DashboardChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authTwoFactorIndexRoute = authTwoFactorIndexRouteImport.update({
  id: '/(auth)/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChatVercelRoute = DashboardChatVercelRouteImport.update({
  id: '/chat/vercel',
  path: '/chat/vercel',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardChatRagRoute = DashboardChatRagRouteImport.update({
  id: '/chat/rag',
  path: '/chat/rag',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const authTwoFactorOtpRoute = authTwoFactorOtpRouteImport.update({
  id: '/(auth)/two-factor/otp',
  path: '/two-factor/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authAcceptInvitationInvitationIdIndexRoute =
  authAcceptInvitationInvitationIdIndexRouteImport.update({
    id: '/(auth)/accept-invitation/$invitationId/',
    path: '/accept-invitation/$invitationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiVercelChatRoute = ApiAiVercelChatRouteImport.update({
  id: '/api/ai/vercel/chat',
  path: '/api/ai/vercel/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMcpTransportRoute = ApiAiMcpTransportRouteImport.update({
  id: '/api/ai/mcp/$transport',
  path: '/api/ai/mcp/$transport',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRagRoute = ApiAiChatRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => ApiAiChatRoute,
} as any)
const ApiAiChatImageGenerationRoute =
  ApiAiChatImageGenerationRouteImport.update({
    id: '/image/generation',
    path: '/image/generation',
    getParentRoute: () => ApiAiChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/layout': typeof authLayoutRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard/protect-examples': typeof DashboardProtectExamplesRoute
  '/dashboard/tanstack-db-example': typeof DashboardTanstackDbExampleRoute
  '/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/two-factor/otp': typeof authTwoFactorOtpRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/chat/rag': typeof DashboardChatRagRoute
  '/dashboard/chat/vercel': typeof DashboardChatVercelRoute
  '/two-factor/': typeof authTwoFactorIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/chat/': typeof DashboardChatIndexRoute
  '/dashboard/settings-enhanced/': typeof DashboardSettingsEnhancedIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/workspace/': typeof DashboardWorkspaceIndexRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportRoute
  '/api/ai/vercel/chat': typeof ApiAiVercelChatRoute
  '/accept-invitation/$invitationId/': typeof authAcceptInvitationInvitationIdIndexRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/layout': typeof authLayoutRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard/protect-examples': typeof DashboardProtectExamplesRoute
  '/dashboard/tanstack-db-example': typeof DashboardTanstackDbExampleRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/two-factor/otp': typeof authTwoFactorOtpRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/chat/rag': typeof DashboardChatRagRoute
  '/dashboard/chat/vercel': typeof DashboardChatVercelRoute
  '/two-factor': typeof authTwoFactorIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/chat': typeof DashboardChatIndexRoute
  '/dashboard/settings-enhanced': typeof DashboardSettingsEnhancedIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/workspace': typeof DashboardWorkspaceIndexRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportRoute
  '/api/ai/vercel/chat': typeof ApiAiVercelChatRoute
  '/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdIndexRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/layout': typeof authLayoutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/dashboard/protect-examples': typeof DashboardProtectExamplesRoute
  '/dashboard/tanstack-db-example': typeof DashboardTanstackDbExampleRoute
  '/(public)/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(auth)/two-factor/otp': typeof authTwoFactorOtpRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/chat/rag': typeof DashboardChatRagRoute
  '/dashboard/chat/vercel': typeof DashboardChatVercelRoute
  '/(auth)/two-factor/': typeof authTwoFactorIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/chat/': typeof DashboardChatIndexRoute
  '/dashboard/settings-enhanced/': typeof DashboardSettingsEnhancedIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/workspace/': typeof DashboardWorkspaceIndexRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportRoute
  '/api/ai/vercel/chat': typeof ApiAiVercelChatRoute
  '/(auth)/accept-invitation/$invitationId/': typeof authAcceptInvitationInvitationIdIndexRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forgot-password'
    | '/layout'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/protect-examples'
    | '/dashboard/tanstack-db-example'
    | '/'
    | '/dashboard/'
    | '/two-factor/otp'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/admin/users'
    | '/dashboard/chat/rag'
    | '/dashboard/chat/vercel'
    | '/two-factor/'
    | '/dashboard/admin/'
    | '/dashboard/chat/'
    | '/dashboard/settings-enhanced/'
    | '/dashboard/settings/'
    | '/dashboard/workspace/'
    | '/api/ai/chat/rag'
    | '/api/ai/mcp/$transport'
    | '/api/ai/vercel/chat'
    | '/accept-invitation/$invitationId/'
    | '/api/ai/chat/image/generation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/layout'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/protect-examples'
    | '/dashboard/tanstack-db-example'
    | '/'
    | '/dashboard'
    | '/two-factor/otp'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/admin/users'
    | '/dashboard/chat/rag'
    | '/dashboard/chat/vercel'
    | '/two-factor'
    | '/dashboard/admin'
    | '/dashboard/chat'
    | '/dashboard/settings-enhanced'
    | '/dashboard/settings'
    | '/dashboard/workspace'
    | '/api/ai/chat/rag'
    | '/api/ai/mcp/$transport'
    | '/api/ai/vercel/chat'
    | '/accept-invitation/$invitationId'
    | '/api/ai/chat/image/generation'
  id:
    | '__root__'
    | '/dashboard'
    | '/(auth)/forgot-password'
    | '/(auth)/layout'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/dashboard/protect-examples'
    | '/dashboard/tanstack-db-example'
    | '/(public)/'
    | '/dashboard/'
    | '/(auth)/two-factor/otp'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/admin/users'
    | '/dashboard/chat/rag'
    | '/dashboard/chat/vercel'
    | '/(auth)/two-factor/'
    | '/dashboard/admin/'
    | '/dashboard/chat/'
    | '/dashboard/settings-enhanced/'
    | '/dashboard/settings/'
    | '/dashboard/workspace/'
    | '/api/ai/chat/rag'
    | '/api/ai/mcp/$transport'
    | '/api/ai/vercel/chat'
    | '/(auth)/accept-invitation/$invitationId/'
    | '/api/ai/chat/image/generation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLayoutRoute: typeof authLayoutRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  publicIndexRoute: typeof publicIndexRoute
  authTwoFactorOtpRoute: typeof authTwoFactorOtpRoute
  ApiAiChatRoute: typeof ApiAiChatRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  authTwoFactorIndexRoute: typeof authTwoFactorIndexRoute
  ApiAiMcpTransportRoute: typeof ApiAiMcpTransportRoute
  ApiAiVercelChatRoute: typeof ApiAiVercelChatRoute
  authAcceptInvitationInvitationIdIndexRoute: typeof authAcceptInvitationInvitationIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tanstack-db-example': {
      id: '/dashboard/tanstack-db-example'
      path: '/tanstack-db-example'
      fullPath: '/dashboard/tanstack-db-example'
      preLoaderRoute: typeof DashboardTanstackDbExampleRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/protect-examples': {
      id: '/dashboard/protect-examples'
      path: '/protect-examples'
      fullPath: '/dashboard/protect-examples'
      preLoaderRoute: typeof DashboardProtectExamplesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/layout': {
      id: '/(auth)/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspace/': {
      id: '/dashboard/workspace/'
      path: '/workspace'
      fullPath: '/dashboard/workspace/'
      preLoaderRoute: typeof DashboardWorkspaceIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings-enhanced/': {
      id: '/dashboard/settings-enhanced/'
      path: '/settings-enhanced'
      fullPath: '/dashboard/settings-enhanced/'
      preLoaderRoute: typeof DashboardSettingsEnhancedIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chat/': {
      id: '/dashboard/chat/'
      path: '/chat'
      fullPath: '/dashboard/chat/'
      preLoaderRoute: typeof DashboardChatIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/two-factor/': {
      id: '/(auth)/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof authTwoFactorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/chat/vercel': {
      id: '/dashboard/chat/vercel'
      path: '/chat/vercel'
      fullPath: '/dashboard/chat/vercel'
      preLoaderRoute: typeof DashboardChatVercelRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/chat/rag': {
      id: '/dashboard/chat/rag'
      path: '/chat/rag'
      fullPath: '/dashboard/chat/rag'
      preLoaderRoute: typeof DashboardChatRagRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/two-factor/otp': {
      id: '/(auth)/two-factor/otp'
      path: '/two-factor/otp'
      fullPath: '/two-factor/otp'
      preLoaderRoute: typeof authTwoFactorOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/accept-invitation/$invitationId/': {
      id: '/(auth)/accept-invitation/$invitationId/'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId/'
      preLoaderRoute: typeof authAcceptInvitationInvitationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/vercel/chat': {
      id: '/api/ai/vercel/chat'
      path: '/api/ai/vercel/chat'
      fullPath: '/api/ai/vercel/chat'
      preLoaderRoute: typeof ApiAiVercelChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/mcp/$transport': {
      id: '/api/ai/mcp/$transport'
      path: '/api/ai/mcp/$transport'
      fullPath: '/api/ai/mcp/$transport'
      preLoaderRoute: typeof ApiAiMcpTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat/rag': {
      id: '/api/ai/chat/rag'
      path: '/rag'
      fullPath: '/api/ai/chat/rag'
      preLoaderRoute: typeof ApiAiChatRagRouteImport
      parentRoute: typeof ApiAiChatRoute
    }
    '/api/ai/chat/image/generation': {
      id: '/api/ai/chat/image/generation'
      path: '/image/generation'
      fullPath: '/api/ai/chat/image/generation'
      preLoaderRoute: typeof ApiAiChatImageGenerationRouteImport
      parentRoute: typeof ApiAiChatRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardProtectExamplesRoute: typeof DashboardProtectExamplesRoute
  DashboardTanstackDbExampleRoute: typeof DashboardTanstackDbExampleRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardChatRagRoute: typeof DashboardChatRagRoute
  DashboardChatVercelRoute: typeof DashboardChatVercelRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardChatIndexRoute: typeof DashboardChatIndexRoute
  DashboardSettingsEnhancedIndexRoute: typeof DashboardSettingsEnhancedIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardWorkspaceIndexRoute: typeof DashboardWorkspaceIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProtectExamplesRoute: DashboardProtectExamplesRoute,
  DashboardTanstackDbExampleRoute: DashboardTanstackDbExampleRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardChatRagRoute: DashboardChatRagRoute,
  DashboardChatVercelRoute: DashboardChatVercelRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardChatIndexRoute: DashboardChatIndexRoute,
  DashboardSettingsEnhancedIndexRoute: DashboardSettingsEnhancedIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardWorkspaceIndexRoute: DashboardWorkspaceIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ApiAiChatRouteChildren {
  ApiAiChatRagRoute: typeof ApiAiChatRagRoute
  ApiAiChatImageGenerationRoute: typeof ApiAiChatImageGenerationRoute
}

const ApiAiChatRouteChildren: ApiAiChatRouteChildren = {
  ApiAiChatRagRoute: ApiAiChatRagRoute,
  ApiAiChatImageGenerationRoute: ApiAiChatImageGenerationRoute,
}

const ApiAiChatRouteWithChildren = ApiAiChatRoute._addFileChildren(
  ApiAiChatRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLayoutRoute: authLayoutRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  publicIndexRoute: publicIndexRoute,
  authTwoFactorOtpRoute: authTwoFactorOtpRoute,
  ApiAiChatRoute: ApiAiChatRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  authTwoFactorIndexRoute: authTwoFactorIndexRoute,
  ApiAiMcpTransportRoute: ApiAiMcpTransportRoute,
  ApiAiVercelChatRoute: ApiAiVercelChatRoute,
  authAcceptInvitationInvitationIdIndexRoute:
    authAcceptInvitationInvitationIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
